language: java
install: mvn install -DskipTests=true -Dgpg.skip=true -Djavadoc.skip=true
script: mvn package -DskipTests=true -Dgpg.skip=true -Djavadoc.skip=true
deploy:
  provider: releases
  api_key:
    secure: ELVhWQO+F3Qgm7zcNdiJom/7aqTLbDu+sYEkQqnOGff46eZr+EbfYDgOZ8YxQQtUd1rAtUKNsZ+udwauFOCIsNNddLz0TYP2j8eCVwlYd3KYa5e4bPbxFqf9eYvAjFiM54ux6BHb0pwfeudJQU+iJPJc4Kx5q7py2tcb1I2D0wNbqO33qoUIcehJsoInY3IH9BUiJb/k2PgYKtDt1/bARfna9C4DAtgoH0whK62XRoozSj8qBJjsTYHiJp4kpY2tWj9vUy9pXVuONY5CrpdLrk5Us7qguUE0FePqkeFCwwg9cI4Kvuf2iVKyr1qAJGCAhBQgK8JD3a8Itwg5n9zHI/lEDpk/g2d/+UfuqccHZSDie5COWTAGOPUCi/jyY9U5z7wRAqT6+H9Ho0Sjkun9wI9rUSgrprOinhuSoLBZ2rHyv/VDT2bcSaZIa3Ks8Bp6hCIcDyOpl1jnreyXMm8tD8lRtsIou8Sssdp5Psy2BXq8PMJ9VrVgJmx6LOjPTsBNvQiFvVoIaWuMPh+3gSpVyHnc2yu+ZqOvkdkIfuejWhcOi59I7lh8HtTDXiwSvWMrMSCPMDe10BGF7FQZrSIYebrJxnOZQWGgXODO0YmXms3iqbo8nkQ3YfZNgKTjEAee0j79HvVgZa03hnGWS/xv3iLVylid3OyesvJZ219zM18=
  file: 'CHANGELOG.md'
  on:
    tags: true
env:
  global:
  - SONATYPE_USERNAME=lymanrb
  - secure: SxuF4re32f2ubtQwGyh3Vhanmk5uc90EarBVO8R1R5R6TuD5RIe0uOih9IY8RQ7uZagYD7aWC90UEctnwxWL96HdD3Hja2nSHHFtnQG/lTpv9NWpEt4S3sKw5mrqSvHphh5tV55fqgUun6IIk0b8ngrTYCmPIUkP4/gn2sAO0BAAkbcSUFWAJq5P98uBoSV805MFxzdsWexixwuF5xqM2TUjh5kpVHmMQ/1J608ti4d48boFYnkrR3TZk0kO2Ajga2ccTGPygvClx67D0X5/2DsolBw5huzFh+6okrVfh43DD8bYNso3hwqYLyAxhUgAEklDxC8JPPSoepi5+8Irg2sSchGF/lRp9jkdJ0pS+Z0Gv3OCQU6B6sX1299SDfKA+8ZE2uU8shHCwrrpSanJzDiLi3Jg89UL9fdaLcAhBCPcZT3xQHhMFqQPdp6WyYQrFhXZN/ngWdk+HKdASgxhK5URuRE1akkNP8Im3PjgNhdnmQ9j4jlw348HhGju9zmtQxzjfpx0k0CxI3FRwW72e4ND5Jn4h1v5cPN9rxuQxMXeYCXRjnTlO3odqhLWtEtSXU/MncIH+P/XqJ0lDJMZPZfHjwYMVMzDRmfUrMmRC4kNgPShm6jgAdhkh3vYSllHVFW04ASxYP5C7ersXGmX75K+/SjfXodGFJ5dUs4GZgU=
  - secure: QC/lToqLXFqKFYwcPdL2MryeSm8vdzCVLn4RqLTImQs2FRupB2lHDC1nQMnTDQlb/3UA3fnxms0hdU9JOdIwqQ6CxvuwPeylMzsRNn75o+X2GtO49tgZkhONTpxYjxtBueFaZtclE3U3ggzaE/kPqDncYGKzEBAfjrIRi8DM5sHwdkq8OBUR06ofIp/UOCSXqGGWNeUz4r5J1CJyARdFag+YEwGZbY0sr4YTXg3SOE+N5wx9B5pa8fsjoyLGCuEo4A+3cfJwZvvj1mM2nkubaOxqDFRlIRTtUUlJdHTnLU+E1bkTHQ0QVFJBDTV0WsGbsMV/MpXifOhaq75SdEyXNUeOUwM+pitbHC1uEzwGAh5O77/TNZsSZDoEgoBhWTO5fLGD0/ngUGQ9/Dch+H98lZ1fF2heM5Z4HKDEUpmgkKm9VbTsKI5zAgRKWjZM8fSuG/+FNq35JbzyoJRzQQUocjeRov1J5xhMXKFdTTdxfGpaqtxgYymrejq8icgM5Vx88ws47oYZBTAI3B1bZLqrQ8+MmtljZHI70DDwx/f1L5Yz41USHxZix/pqmuBpoq3KiPTnIPg0SAss1mg5M9xxDts4RqBDecL5WCSc9kW4pLNvtJ5ci1we+SWgWLH94YO4YfFgJKYQ90WiakFXQrwSqMVYLCHW4kx+3lpYgEDlyy8=
after_deploy:
- echo "deploying to maven central"
- gpg --import secret.key.asc
- mvn deploy --settings settings.xml -DskipTests=true -Dgpg.passphrase=$GPG_PASSPHRASE
before_install:
- openssl aes-256-cbc -K $encrypted_f86dc6d297df_key -iv $encrypted_f86dc6d297df_iv
  -in secret.key.asc.enc -out secret.key.asc -d
